### ISSUE TITLE
Examples with svelte-kit

### ISSUE THREAD

**Issue by flakolefluk** [flakolefluk/web-components-with-svelte#3]
investigate how the same concepts in the blog post can be used with svelte-kit. can we do the same using svelte.config.js configuration file?

**Comment by VoiceOfSoftware** [comment]
I'm trying to follow these instructions https://dev.to/silvio/how-to-create-a-web-components-in-svelte-2g4j but I don't understand where to put <svelte:options tag="svelte-clock">, because there's no App.svelte file in my SvelteKit project. Is there an equivalent place to put that?

**Comment by VoiceOfSoftware** [comment]
I added the import {svelte} and vite section, but get the following error in the browser now

ParseError: Expected }
    at error (file:///Users/granthulbert/Documents/Grant%20Web%20Dev/questhaven3/node_modules/svelte/compiler.mjs:17700:19)
    at Parser$1.error (file:///Users/granthulbert/Documents/Grant%20Web%20Dev/questhaven3/node_modules/svelte/compiler.mjs:17776:9)
    at Parser$1.eat (file:///Users/granthulbert/Documents/Grant%20Web%20Dev/questhaven3/node_modules/svelte/compiler.mjs:17790:18)
    at mustache (file:///Users/granthulbert/Documents/Grant%20Web%20Dev/questhaven3/node_modules/svelte/compiler.mjs:17593:16)
    at new Parser$1 (file:///Users/granthulbert/Documents/Grant%20Web%20Dev/questhaven3/node_modules/svelte/compiler.mjs:17735:21)
    at parse$3 (file:///Users/granthulbert/Documents/Grant%20Web%20Dev/questhaven3/node_modules/svelte/compiler.mjs:17867:20)
    at compile (file:///Users/granthulbert/Documents/Grant%20Web%20Dev/questhaven3/node_modules/svelte/compiler.mjs:31339:17)
    at compileSvelte2 (file:///Users/granthulbert/Documents/Grant%20Web%20Dev/questhaven3/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:313:20)
    at async TransformContext.transform (file:///Users/granthulbert/Documents/Grant%20Web%20Dev/questhaven3/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1460:27)
    at async Object.transform (/Users/granthulbert/Documents/Grant Web Dev/questhaven3/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42396:30)
